version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    environment:
      - OPENAI_KEY
      - GEMINI_KEY
      - CLAUDEAI_KEY
      - MISTRAL_KEY
      - OLLAMA_URL=http://ollama:11434
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    depends_on:
      - backend
    ports:
      - "3000:3000" 
  
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          memory: 10G
          cpus: "2.0"
        reservations:
          memory: 6G
          cpus: "1.0" 
    environment:
      - OLLAMA_HOST=0.0.0.0

volumes:
  ollama:
