version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    environment:
      - OPENAI_KEY
      - GEMINI_KEY
      - CLAUDEAI_KEY
      - MISTRAL_KEY
      - OLLAMA_URL=http://ollama:11434
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - ollama

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    depends_on:
      - backend
    ports:
      - "3000:3000" 
  
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:

